plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.fitmate.app'
    compileSdk 34

    defaultConfig {
        applicationId "ai.fitmate.app"
        minSdk 24
        targetSdk 34
        versionCode 104
        versionName "1.0.4-phase1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.core:core:1.12.0'
}
